# From the NumPy Documentation

https://numpy.org/doc/stable/user/whatisnumpy.html

***

In [4]:
import numpy as np

np = numpy<br>
arrange(n) = creates an array the length of n. starts at zero<br>
reshape = gives a shape to the array (rows, columns<br>
NOTE - (-1) is important. (-1, 5) it will work out the rows needed based on the columns and vice versa. AKA figure it out yourself

In [5]:
a = np.arange(15).reshape(3, 5)

creating an array of 15. starting at zero (0-14)<br>
reshapes the array (3 rows, 5 columns)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

NOTE - numpy range function will deal with floating point numbers. Python will not!<br>
shape - of an array is the number of elements in each dimension

In [6]:
a.shape

(3, 5)

ndim - function return the number of dimensions of an array

In [7]:
a.ndim

2

dtype - Type of the data (integer, float, Python object, etc.)

In [8]:
a.dtype

dtype('int32')

itemsize - returns the size (in bytes) of each element of a NumPy array

In [9]:
a.itemsize

4

size - function count the number of elements

In [10]:
a.size

15

linspace - creates numeric sequences<br>
linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [22]:
b = np.linspace(0.0, 10.0, 101)

In [23]:
b

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

zero - Return a new array of given shape and type, filled with zeros.<br>
numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

ones - replica of zero, but returns filled with ones

In [27]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

eye - return a 2-D array with ones on the diagonal and zeros elsewhere.<br>
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [30]:
c = np.eye(3)

In [31]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
c.dtype

dtype('float64')

astype - Copy of the array, cast to a specified type. float to int. 

In [33]:
c.astype('int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

slicing - taking elements from one given index to another given index<br>
We pass slice instead of index like this: [start:end].<br>
We can also define the step, like this: [start:end:step].<br>
If we don't pass start its considered 0<br>
If we don't pass end its considered length of array in that dimension<br>
If we don't pass step its considered 1

In [35]:
c[1:2]

array([[0., 1., 0.]])

In [36]:
c[1:]

array([[0., 1., 0.],
       [0., 0., 1.]])

In [37]:
c[:2]

array([[1., 0., 0.],
       [0., 1., 0.]])

In [42]:
c[1:1:1]

array([], shape=(0, 3), dtype=float64)

***

# End